package com.sun.org.omg.CORBA;


/**
* com/sun/org/omg/CORBA/IDLTypeOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ir.idl
*/
public interface IDLTypeOperations  extends com.sun.org.omg.CORBA.IRObjectOperations
{
    org.omg.CORBA.TypeCode type ();
} // interface IDLTypeOperations
