package com.sun.org.omg.CORBA;


/**
* com/sun/org/omg/CORBA/IRObjectOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ir.idl
*/

// This file has been manually _CHANGED_

public interface IRObjectOperations
{

    // read interface

    // _CHANGED_
    //com.sun.org.omg.CORBA.DefinitionKind def_kind ();
    org.omg.CORBA.DefinitionKind def_kind ();

    // write interface
    void destroy ();
} // interface IRObjectOperations
