package com.sun.org.omg.SendingContext;


/**
* com/sun/org/omg/SendingContext/CodeBase.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from rt.idl
*/

// Edited to leave RunTime in org.omg.CORBA

public interface CodeBase extends CodeBaseOperations, org.omg.SendingContext.RunTime, org.omg.CORBA.portable.IDLEntity
{
} // interface CodeBase
