package jdk.nashorn.internal.runtime.linker;

/**
 * Represents a an adapter for invoking superclass methods on an adapter instance generated by
 * {@link JavaAdapterBytecodeGenerator}. Note that objects of this class are just wrappers around the adapter instances,
 * without any behavior. All the behavior is defined in the {@code JavaSuperAdapterLinker}.
 */
class JavaSuperAdapter {
    private final Object adapter;

    JavaSuperAdapter(final Object adapter) {
        adapter.getClass(); // NPE check
        this.adapter = adapter;
    }

    public Object getAdapter() {
        return adapter;
    }
}
