
#ifndef CPU_ZERO_VM_TEMPLATEINTERPRETERGENERATOR_ZERO_HPP
#define CPU_ZERO_VM_TEMPLATEINTERPRETERGENERATOR_ZERO_HPP

// This file is intentionally empty

#endif // CPU_ZERO_VM_TEMPLATEINTERPRETERGENERATOR_ZERO_HPP
