package com.sun.xml.internal.ws.api.message;

import javax.xml.ws.WebServiceFeature;

/**
 * Suppresses automatic generation of WS-Addressing headers in request messages.  Use this in cases
 * where required headers will be generated by other means.
 */
public class SuppressAutomaticWSARequestHeadersFeature extends
                WebServiceFeature {

        public SuppressAutomaticWSARequestHeadersFeature() {
                enabled = true;
        }

        @Override
        public String getID() {
                return SuppressAutomaticWSARequestHeadersFeature.class.toString();
        }

}
