package com.sun.tools.doclets.formats.html.markup;

/**
 * Enum representing HTML styles. The name map to values in the CSS file.
 *
 *  <p><b>This is NOT part of any supported API.
 *  If you write code that depends on this, you do so at your own risk.
 *  This code and its internal interfaces are subject to change or
 *  deletion without notice.</b>
 */
public enum HtmlStyle {
    aboutLanguage,
    activeTableTab,
    altColor,
    bar,
    block,
    blockList,
    blockListLast,
    bottomNav,
    classUseContainer,
    colFirst,
    colLast,
    colOne,
    constantsSummary,
    constantValuesContainer,
    contentContainer,
    deprecatedContent,
    deprecatedLabel,
    deprecatedSummary,
    deprecationComment,
    description,
    descfrmTypeLabel,
    details,
    docSummary,
    emphasizedPhrase,
    header,
    horizontal,
    footer,
    indexContainer,
    indexHeader,
    inheritance,
    interfaceName,
    legalCopy,
    memberNameLabel,
    memberNameLink,
    memberSummary,
    nameValue,
    navBarCell1Rev,
    navList,
    overrideSpecifyLabel,
    overviewSummary,
    packageHierarchyLabel,
    paramLabel,
    returnLabel,
    rowColor,
    seeLabel,
    serializedFormContainer,
    simpleTagLabel,
    skipNav,
    sourceContainer,
    sourceLineNo,
    subNav,
    subNavList,
    subTitle,
    summary,
    tabEnd,
    tableTab,
    throwsLabel,
    title,
    topNav,
    typeNameLabel,
    typeNameLink,
    typeSummary,
    useSummary;
}
